USE [master]
GO

/****** Object:  Database [AdmUsuarios]    Script Date: 5/08/2021 7:20:53 a. m. ******/
CREATE DATABASE [AdmUsuarios]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdmUsuarios', FILENAME = N'C:\EPS\AdmUsuarios.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AdmUsuarios_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\AdmUsuarios_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdmUsuarios].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [AdmUsuarios] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [AdmUsuarios] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [AdmUsuarios] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [AdmUsuarios] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [AdmUsuarios] SET ARITHABORT OFF 
GO

ALTER DATABASE [AdmUsuarios] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [AdmUsuarios] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [AdmUsuarios] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [AdmUsuarios] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [AdmUsuarios] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [AdmUsuarios] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [AdmUsuarios] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [AdmUsuarios] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [AdmUsuarios] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [AdmUsuarios] SET  DISABLE_BROKER 
GO

ALTER DATABASE [AdmUsuarios] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [AdmUsuarios] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [AdmUsuarios] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [AdmUsuarios] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [AdmUsuarios] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [AdmUsuarios] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [AdmUsuarios] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [AdmUsuarios] SET RECOVERY FULL 
GO

ALTER DATABASE [AdmUsuarios] SET  MULTI_USER 
GO

ALTER DATABASE [AdmUsuarios] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [AdmUsuarios] SET DB_CHAINING OFF 
GO

ALTER DATABASE [AdmUsuarios] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [AdmUsuarios] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [AdmUsuarios] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [AdmUsuarios] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [AdmUsuarios] SET QUERY_STORE = OFF
GO

ALTER DATABASE [AdmUsuarios] SET  READ_WRITE 
GO


